version: '3.9'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
    - "5432:5432"
  web:
    build: .
    ports:
    - '3000:3000'
    volumes:
      - .:/app
    depends_on:
      - db