---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/products":
    post:
      summary: Create Product
      tags:
      - Products
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '201':
          description: product created
        '400':
          description: Invalid Request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                description:
                  type: string
                tipo:
                  type: string
                precio:
                  type: number
                  format: float
                stock:
                  type: integer
              required:
              - nombre
              - tipo
              - precio
  "/api/v1/users":
    get:
      summary: list users
      responses:
        '200':
          description: successful
    post:
      summary: create user
      responses:
        '200':
          description: successful
  "/api/v1/users/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show user
      responses:
        '200':
          description: successful
    patch:
      summary: update user
      responses:
        '200':
          description: successful
    put:
      summary: update user
      responses:
        '200':
          description: successful
    delete:
      summary: delete user
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
securityDefinitions:
  bearerAuth:
    type: apiKey
    name: Authorization
    in: header
security:
- bearerAuth: []
